# Generated by Django 4.2 on 2023-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=35)),
                ('Password', models.CharField(default='', max_length=35)),
                ('FirstName', models.CharField(default='', max_length=35)),
                ('LastName', models.CharField(default='', max_length=35)),
                ('Role', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=1)),
            ],
        ),
    ]
